### ISSUE TITLE
GitHub Dependabot Task Fails - `security_advisory_response': undefined method `[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by resnickio** [KennaSecurity/toolkit#337]
When running the GitHub Dependabot task it fails with the following errors, both when running as a standalone Docker container and built through a GitHub Action.

Docker:
```bash
docker run -it --rm -t kennasecurity/toolkit:latest task=github_dependabot github_access_token=******* github_organization_name=*******
Running: Kenna::Toolkit::GithubDependabot
[+] (20220125151343) Setting kenna_api_host to default value: api.kennasecurity.com
[+] (20220125151343) Setting output_directory to default value: output/github_dependabot
[+] (20220125151343) Got option: task: github_dependabot
[+] (20220125151343) Got option: github_access_token: *******
[+] (20220125151343) Got option: github_organization_name: *******
[+] (20220125151343) Got option: kenna_api_host: api.kennasecurity.com
[+] (20220125151343) Got option: output_directory: output/github_dependabot
[+] (20220125151343)
[+] (20220125151343) Launching the github_dependabot Vulnerabilities task!
[+] (20220125151343)
/opt/app/toolkit/tasks/connectors/github_dependabot/lib/github_dependabot_client.rb:20:in `security_advisory_response': undefined method `[]' for nil:NilClass (NoMethodError)
        from /opt/app/toolkit/tasks/connectors/github_dependabot/github_dependabot.rb:52:in `run'
        from toolkit.rb:55:in `<main>'
```

GitHub Action Logs:
```
2022-01-25T15:18:09.8165355Z ##[group]Run exec bundle exec ruby toolkit.rb task=github_dependabot github_access_token=*** github_organization_name=*** kenna_api_key=*** kenna_connector_id=***
2022-01-25T15:18:09.8166115Z [36;1mexec bundle exec ruby toolkit.rb task=github_dependabot github_access_token=*** github_organization_name=*** kenna_api_key=*** kenna_connector_id=***[0m
2022-01-25T15:18:09.8210834Z shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
2022-01-25T15:18:09.8211086Z ##[endgroup]
2022-01-25T15:18:09.8256251Z ##[debug]/usr/bin/bash --noprofile --norc -e -o pipefail /home/runner/work/_temp/3d8519bf-58f8-4ba5-aab6-5cb7ce3b0a62.sh
2022-01-25T15:18:11.1965448Z /home/runner/work/CloudSec-dependabot-kdi-action/CloudSec-dependabot-kdi-action/toolkit/tasks/connectors/github_dependabot/lib/github_dependabot_client.rb:20:in `security_advisory_response': undefined method `[]' for nil:NilClass (NoMethodError)
2022-01-25T15:18:11.1966626Z 	from /home/runner/work/CloudSec-dependabot-kdi-action/CloudSec-dependabot-kdi-action/toolkit/tasks/connectors/github_dependabot/github_dependabot.rb:52:in `run'
2022-01-25T15:18:11.1967151Z 	from toolkit.rb:55:in `<main>'
2022-01-25T15:18:11.1997669Z Running: Kenna::Toolkit::GithubDependabot
2022-01-25T15:18:11.1998323Z [+] (20220125151811) Setting kenna_api_host to default value: api.kennasecurity.com
2022-01-25T15:18:11.1998717Z [+] (20220125151811) Setting output_directory to default value: output/github_dependabot
2022-01-25T15:18:11.1999081Z [+] (20220125151811) Got option: task: github_dependabot
2022-01-25T15:18:11.1999398Z [+] (20220125151811) Got option: github_access_token: ***
2022-01-25T15:18:11.1999725Z [+] (20220125151811) Got option: github_organization_name: ***
2022-01-25T15:18:11.2000051Z [+] (20220125151811) Got option: kenna_api_key: ***
2022-01-25T15:18:11.2000357Z [+] (20220125151811) Got option: kenna_connector_id: ***
2022-01-25T15:18:11.2000680Z [+] (20220125151811) Got option: kenna_api_host: api.kennasecurity.com
2022-01-25T15:18:11.2001014Z [+] (20220125151811) Got option: output_directory: output/github_dependabot
2022-01-25T15:18:11.2001284Z [+] (20220125151811) 
2022-01-25T15:18:11.2001573Z [+] (20220125151811) Launching the github_dependabot Vulnerabilities task!
2022-01-25T15:18:11.2001848Z [+] (20220125151811) 
2022-01-25T15:18:11.2043811Z ##[error]Process completed with exit code 1.
```

**Comment by jscalvo** [comment]
Hi, we pushed a new version of this connector to the `main` branch. This new version would show you if any error occurs while retrieving data from GitHub. Can you try again?
At the same time, I'm also reviewing this connector so your input will be really valuable for us.

**Comment by resnickio** [comment]
Thanks for that quick update, being able to see the API error now is really helpful. After updating the GitHub PAT with the permission scope from the error it now works.

```bash
docker run -it --rm -t kennasecurity/toolkit:latest task=github_dependabot github_access_token=*** github_organization_name=***
Running: Kenna::Toolkit::GithubDependabot
[+] (20220125204323) Setting kenna_api_host to default value: api.kennasecurity.com
[+] (20220125204323) Setting output_directory to default value: output/github_dependabot
[+] (20220125204323) Got option: task: github_dependabot
[+] (20220125204323) Got option: github_access_token: ***
[+] (20220125204323) Got option: github_organization_name: ***
[+] (20220125204323) Got option: kenna_api_host: api.kennasecurity.com
[+] (20220125204323) Got option: output_directory: output/github_dependabot
[+] (20220125204323)
[+] (20220125204323) Launching the github_dependabot Vulnerabilities task!
[+] (20220125204323)
/opt/app/toolkit/tasks/connectors/github_dependabot/lib/github_dependabot_client.rb:21:in `security_advisory_response': Unable to retrieve data. GitHub GraphQL API returned the following errors: (Kenna::Toolkit::GithubDependabotModule::GithubDependabotClient::ApiError)

[INSUFFICIENT_SCOPES] Your token has not been granted the required scopes to execute this query. The 'id' field requires one of the following scopes: ['public_repo'], but your token has only been granted the: ['read:enterprise', 'read:org', 'security_events'] scopes. Please modify your token's scopes at: https://github.com/settings/tokens.
        from /opt/app/toolkit/tasks/connectors/github_dependabot/github_dependabot.rb:52:in `run'
        from toolkit.rb:55:in `<main>'
```
