### ISSUE TITLE
Microsoft Defender ATP connector crashes on startup

### ISSUE THREAD

**Issue by whitfieldsdad** [KennaSecurity/toolkit#440]
The Microsoft Defender for Endpoint (ATP) connector crashes on startup:

```
$ ./run-ms-defender-atp-connector.sh 
Running: Kenna::Toolkit::MSDefenderAtp
[+] (20221027152342) Setting atp_api_host to default value: api.securitycenter.microsoft.com
[+] (20221027152342) Setting atp_oath_host to default value: login.windows.net
[+] (20221027152342) Setting kenna_api_host to default value: api.kennasecurity.com
[+] (20221027152342) Setting batch_page_size to default value: 500
[+] (20221027152342) Setting max_retries to default value: 5
[+] (20221027152342) Converting max_retries with input value nil to 5.
[+] (20221027152342) Setting output_directory to default value: output/microsoft_atp
[+] (20221027152342) Got option: task: ms_defender_atp
[+] (20221027152342) Got option: kenna_api_key: E*******qhe
[+] (20221027152342) Got option: kenna_api_host: api.kennasecurity.com
[+] (20221027152342) Got option: kenna_connector_id: ***********
[+] (20221027152342) Got option: atp_tenant_id: ***********
[+] (20221027152342) Got option: atp_client_id: ***********
[+] (20221027152342) Got option: atp_client_secret: ***********
[+] (20221027152342) Got option: batch_page_size: 10000
[+] (20221027152342) Got option: atp_api_host: api.securitycenter.microsoft.com
[+] (20221027152342) Got option: atp_oath_host: login.windows.net
[+] (20221027152342) Got option: file_cleanup: 
[+] (20221027152342) Got option: max_retries: 5
[+] (20221027152342) Got option: output_directory: output/microsoft_atp
[+] (20221027152342) 
[+] (20221027152342) Launching the MS Defender ATP task!
[+] (20221027152343) 
[!] (20221027152358) Unable to process response!
/opt/app/toolkit/tasks/connectors/ms_defender_atp/ms_defender_atp.rb:138:in `run': undefined method `key?' for nil:NilClass (NoMethodError)

        asset_next_link = asset_json_response.fetch("@odata.nextLink") if asset_json_response.key?("@odata.nextLink")
                                                                                             ^^^^^
        from toolkit.rb:57:in `<main>'
```

**Comment by whitfieldsdad** [comment]
Moving to support ticket
